version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: travel-planner-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: travel-planner
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - travel-planner-network

  ai-service:
    build: .
    container_name: travel-planner-ai
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/travel-planner
      - OLLAMA_HOST=http://host.docker.internal:11434
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/logs
    networks:
      - travel-planner-network

volumes:
  mongodb_data:

networks:
  travel-planner-network:
    driver: bridge
